### ISSUE TITLE
QUESTION FOR SIR MIKE

### ISSUE THREAD

**Issue by koykoy027** [Real-Faith-Solutions/career-executive-service-board#297]
### LEGACY SYSTEM
- in Plantilla position manager, meaning of 'None' in occupant (boolean in database, but theres name value in legacy system)
![image](https://github.com/Real-Faith-Solutions/career-executive-service-board/assets/96485178/25be741a-9bdb-47be-9b0a-38f4c1719080)

---

- difference between appointee and occupant
- occupant and occupant status is missing on database
- is occupant and occupied are the same?
![image](https://github.com/Real-Faith-Solutions/career-executive-service-board/assets/96485178/9ca78508-40eb-4659-9fc2-452bae3ce879)

**Comment by jonathan-llemit-dev** [comment]
EXECUTIVE 201 PROFILE REPORTS

- List of Active CESOs, CES Eligibles and CSEEs (defined / filtered / grouped by appointing Authority) 
- List of Active CESOs, CES Eligibles and CSEEs (defined / filtered / grouped by appointing Authority) 
- Statistic Summary per Presidential Appointments

**Comment by koykoy027** [comment]
done
